input: md
output: static
template: static/template.html

headings:
  h1: text-4xl mb-4 mt-8 font-display opacity-90 font-black text-c-text-2
  h2: text-2xl mt-10 mb-4 font-display opacity-90 font-bold text-c-text-2
  h3: text-xl mt-10 mb-4 font-display opacity-90 text-c-text-2

file_tree_title_classes: "uppercase font-display text-c-text-2 font-medium"
link_classes: text-blue-500 hover:underline
